#!/bin/sh

set -x

aclocal

autoheader

automake --foreign --add-missing --copy \
	Makefile \
	etc/Makefile \
	src/Makefile \
	www/Makefile \
	var/Makefile \
	var/lib/Makefile \
	var/lib/rrd/Makefile

autoconf
