all :
	@echo "Making Images"
	batik-rasterizer -h 12 arrow.svg
	batik-rasterizer -h 15 disk.svg
	batik-rasterizer -h 15 viewgraph.svg
	batik-rasterizer -h 35 -d netmrg-logo-small.png netmrg-logo.svg
	batik-rasterizer -h 100 -d netmrg-logo-medium.png netmrg-logo.svg
	batik-rasterizer -h 250 -d netmrg-logo-large.png netmrg-logo.svg
	batik-rasterizer -h 15 status-unknown-trig.svg
	batik-rasterizer -h 15 status-unknown-untrig.svg
	batik-rasterizer -h 15 status-good-trig.svg
	batik-rasterizer -h 15 status-good-untrig.svg
	batik-rasterizer -h 15 status-warning-trig.svg
	batik-rasterizer -h 15 status-warning-untrig.svg
	batik-rasterizer -h 15 status-critical-trig.svg
	batik-rasterizer -h 15 status-critical-untrig.svg

